<a href="https://colab.research.google.com/github/tanvimeshram893-pixel/syntaxhub/blob/main/Copy_of_Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import ast
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

LOAD DATASET

In [ ]:
movies=pd.read_csv("/content/drive/MyDrive/tmdb_5000_movies.csv")
credits=pd.read_csv("/content/drive/MyDrive/tmdb_5000_credits.csv")

/tmp/ipykernel_6791/777584609.py:2: DtypeWarning: Columns (0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264) have mixed types. Specify dtype option on import or set low_memory=False.
  credits=pd.read_csv("/content/drive/MyDrive/tmdb_5000_credits.csv")

In [ ]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
credits.head()

,movie_id,title,cast,crew,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

MERGE DATASET

In [ ]:
movies = movies.merge(credits, on='title')

In [ ]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

SELECT IMPORTANT COLUMNS

In [ ]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        4
dtype: int64

DATA CLEANING

In [ ]:
movies.dropna(inplace=True)

In [ ]:
movies.duplicated().sum()

np.int64(0)

In [ ]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
def convert(obj):
  L=[]
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [ ]:
movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4802, dtype: object

In [ ]:
movies['genres']=movies['genres'].apply(convert)

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies['keywords'].apply(convert)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4802, dtype: object

In [ ]:
movies['keywords']=movies['keywords'].apply(convert)

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

TOP 3 CAST

In [ ]:
def convert3(obj):
  L=[]
  counter=0
  for i in ast.literal_eval(obj):
    if counter < 3:
      L.append(i['name'])
      counter+=1
    else:
      break
  return L

In [ ]:
movies['cast'].apply(convert3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4802, dtype: object

In [ ]:
movies['cast']=movies['cast'].apply(convert3)

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

DIRECTOR EXTRACTION

In [ ]:
def fetch_director(obj):
  L=[]
  try:
    for i in ast.literal_eval(obj):
      if i['job']=='Director':
        L.append(i['name'])
        break
  except (ValueError, SyntaxError): # Catch errors from malformed string literals
    return [] # Return an empty list or handle as appropriate
  return L

In [ ]:
movies['crew'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4802, dtype: object

In [ ]:
movies['crew']=movies['crew'].apply(fetch_director)

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

CONVERT OVERVIEW TO LIST

In [ ]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4802, dtype: object

In [ ]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

REMOVE SPACES

In [ ]:
movies['genres'].apply(lambda x:[i.replace(" "," ") for i in x])

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4802, dtype: object

In [ ]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" "," ") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" "," ") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" "," ") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" "," ") for i in x])

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

CREATE TAGS COLUMN

In [ ]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
new_df = movies[['movie_id','title','tags']]

In [ ]:
new_df['tags'].apply(lambda x: " ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4802, dtype: object

In [ ]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

/tmp/ipykernel_6791/1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [ ]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [ ]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Sam Worthington Zoe Saldana Sigourney Weaver James Cameron'

In [ ]:
new_df['tags'].apply(lambda x:x.lower())

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4802, dtype: object

In [ ]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_6791/4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [ ]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [ ]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy science fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d sam worthington zoe saldana sigourney weaver james cameron'

In [ ]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drug abuse exotic island east india trading company love of one's life traitor shipwreck strong woman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnny depp orlando bloom keira knightley gore verbinski"

Vectorization + Cosine Similarity

In [ ]:
cv = CountVectorizer(max_features=5000, stop_words='english')

In [ ]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
similarity = cosine_similarity(vectors)

In [ ]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(2402, np.float64(0.48074115106715354)),
 (1530, np.float64(0.4333408306443943)),
 (3157, np.float64(0.42808533691623324)),
 (835, np.float64(0.39558756904487125)),
 (4332, np.float64(0.38949041885226005))]

Recommendation Function

In [ ]:
def recommend(movie):
    if movie not in new_df['title'].values:
        print("Movie not found!")
        return

    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]

    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    print(f"\nRecommendations for {movie}:")
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [ ]:
def recommend(movie):
  movie_index=new_df[new_df['title']==movie].index[0]
  distances=similarity[movie_index]
  movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
  for i in movies_list:
    print(new_df.iloc[i[0]].title)

Sample Queries (Evaluation)

In [ ]:
recommend('Avatar')

Aliens
Moonraker
Alien
Alien³
Silent Running

In [ ]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman
Batman & Robin

In [ ]:
recommend("Titanic")

The Notebook
Romance & Cigarettes
Captain Phillips
Veer-Zaara
Four Weddings and a Funeral

In [ ]:
import pickle

In [ ]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [ ]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [ ]:
new_df.to_dict()

{'movie_id': {0: '19995',
  1: '285',
  2: '206647',
  3: '49026',
  4: '49529',
  5: '559',
  6: '38757',
  7: '99861',
  8: '767',
  9: '209112',
  10: '1452',
  11: '10764',
  12: '58',
  13: '57201',
  14: '49521',
  15: '2454',
  16: '24428',
  17: '1865',
  18: '41154',
  19: '122917',
  20: '1930',
  21: '20662',
  22: '57158',
  23: '2268',
  24: '254',
  25: '597',
  26: '271110',
  27: '44833',
  28: '135397',
  29: '37724',
  30: '558',
  31: '68721',
  32: '12155',
  33: '36668',
  34: '62211',
  35: '8373',
  36: '91314',
  37: '68728',
  38: '102382',
  39: '20526',
  40: '49013',
  41: '44912',
  42: '10193',
  43: '534',
  44: '168259',
  45: '72190',
  46: '127585',
  47: '54138',
  48: '81005',
  49: '64682',
  50: '9543',
  51: '68726',
  52: '38356',
  53: '217',
  54: '105864',
  55: '62177',
  56: '188927',
  57: '10681',
  58: '5174',
  59: '14161',
  60: '17979',
  61: '76757',
  62: '258489',
  63: '411',
  64: '246655',
  65: '155',
  66: '14160',
  67: '15512',
  68: '1726',
  69: '44826',
  70: '8487',
  71: '1735',
  72: '297761',
  73: '2698',
  74: '137113',
  75: '9804',
  76: '14869',
  77: '150540',
  78: '278927',
  79: '10138',
  80: '58595',
  81: '102651',
  82: '119450',
  83: '79698',
  84: '64686',
  85: '100402',
  86: '10192',
  87: '158852',
  88: '177572',
  89: '82690',
  90: '5255',
  91: '47933',
  92: '10191',
  93: '296',
  94: '118340',
  95: '157336',
  96: '27205',
  97: '315011',
  98: '49051',
  99: '9799',
  100: '4922',
  101: '49538',
  102: '131634',
  103: '27022',
  104: '503',
  105: '241259',
  106: '810',
  107: '68735',
  108: '87101',
  109: '10140',
  110: '676',
  111: '1858',
  112: '1966',
  113: '675',
  114: '674',
  115: '8960',
  116: '6479',
  117: '118',
  118: '2062',
  119: '272',
  120: '10527',
  121: '18360',
  122: '2080',
  123: '605',
  124: '109445',
  125: '604',
  126: '76338',
  127: '76341',
  128: '13448',
  129: '10195',
  130: '13053',
  131: '19585',
  132: '57165',
  133: '62213',
  134: '177677',
  135: '7978',
  136: '5559',
  137: '49444',
  138: '10196',
  139: '956',
  140: '117251',
  141: '50321',
  142: '11619',
  143: '266647',
  144: '82703',
  145: '652',
  146: '80321',
  147: '36669',
  148: '43074',
  149: '95',
  150: '608',
  151: '2310',
  152: '140300',
  153: '56292',
  154: '81188',
  155: '7552',
  156: '616',
  157: '147441',
  158: '13475',
  159: '557',
  160: '82702',
  161: '205584',
  162: '10048',
  163: '13183',
  164: '944',
  165: '1927',
  166: '72559',
  167: '7364',
  168: '2114',
  169: '1771',
  170: '36643',
  171: '8619',
  172: '50620',
  173: '65759',
  174: '1724',
  175: '267935',
  176: '281957',
  177: '77950',
  178: '44896',
  179: '270946',
  180: '2503',
  181: '9502',
  182: '102899',
  183: '101299',
  184: '228161',
  185: '74',
  186: '8961',
  187: '417859',
  188: '27576',
  189: '86834',
  190: '17578',
  191: '673',
  192: '6972',
  193: '82700',
  194: '10567',
  195: '181533',
  196: '38055',
  197: '671',
  198: '49524',
  199: '22',
  200: '131631',
  201: '591',
  202: '172385',
  203: '36658',
  204: '51497',
  205: '58574',
  206: '18823',
  207: '861',
  208: '1911',
  209: '49040',
  210: '415',
  211: '8871',
  212: '435',
  213: '955',
  214: '2133',
  215: '1979',
  216: '87827',
  217: '1250',
  219: '9471',
  220: '70981',
  221: '10996',
  222: '68724',
  223: '2789',
  224: '97020',
  225: '7459',
  226: '42888',
  227: '37834',
  228: '75612',
  229: '1895',
  230: '1894',
  231: '585',
  232: '76170',
  233: '1893',
  234: '49519',
  235: '2395',
  236: '12100',
  237: '290595',
  238: '98566',
  239: '49047',
  240: '9619',
  241: '308531',
  242: '166424',
  243: '1593',
  244: '254128',
  245: '714',
  246: '2024',
  247: '163',
  248: '787',
  249: '262500',
  250: '2567',
  251: '38745',
  252: '40805',
  253: '53182',
  254: '41513',
  255: '13700',
  256: '262504',
  257: '39254',
  258: '77931',
  259: '1639',
  260: '80274',
  261: '1571',
  262: '120',
  263: '10204',
  264: '8489',
  265: '10588',
  266: '2048',
  267: '1495',
  268: '10137',
  269: '10198',
  270: '286217',
  271: '1635',
  272: '24113',
  273: '9679',
  274: '98',
  275: '180',
  276: '672',
  277: '36557',
  278: '869',
  279: '280',
  280: '11322',
  281: '4982',
  282: '36955',
  283: '18487',
  284: '39451',
  285: '27581',
  286: '9268',
  287: '68718',
  288: '10545',
  289: '11688',
  290: '76163',
  291: '2059',
  292: '2486',
  293: '16523',
  294: '116711',
  295: '37710',
  296: '9946',
  297: '1372',
  298: '106646',
  299: '414',
  300: '563',
  301: '83542',
  302: '41216',
  303: '314',
  304: '184315',
  305: '9016',
  306: '18162',
  307: '138103',
  308: '257088',
  309: '10214',
  310: '205775',
  311: '11692',
  312: '22972',
  313: '227973',
  314: '29193',
  315: '1734',
  316: '3131',
  317: '76758',
  318: '9408',
  319: '9890',
  320: '855',
  321: '77953',
  322: '18',
  323: '37786',
  324: '10501',
  325: '57800',
  326: '150689',
  327: '7980',
  328: '12',
  329: '122',
  330: '121',
  331: '68737',
  332: '1995',
  333: '157353',
  334: '331',
  335: '61791',
  336: '8204',
  337: '47964',
  338: '10733',
  339: '9806',
  340: '1408',
  341: '32657',
  342: '607',
  343: '863',
  344: '44048',
  345: '5175',
  346: '2655',
  347: '22794',
  348: '8355',
  349: '116745',
  350: '4327',
  351: '1422',
  352: '10674',
  353: '7446',
  354: '65754',
  355: '1572',
  356: '10528',
  357: '271969',
  358: '10865',
  359: '258509',
  360: '2253',
  361: '10661',
  362: '257344',
  363: '644',
  364: '10756',
  365: '686',
  366: '9383',
  367: '179',
  368: '76285',
  369: '1996',
  370: '291805',
  371: '10003',
  372: '1535',
  373: '2067',
  374: '46195',
  375: '2277',
  376: '10357',
  377: '4477',
  378: '8665',
  379: '9387',
  380: '921',
  381: '49852',
  382: '4464',
  383: '664',
  384: '8358',
  385: '9836',
  386: '2502',
  387: '9772',
  388: '161',
  389: '52451',
  390: '76492',
  391: '4523',
  392: '59961',
  393: '10481',
  394: '59108',
  395: '1581',
  396: '9798',
  397: '22897',
  398: '298',
  399: '7484',
  400: '157350',
  401: '853',
  402: '10159',
  403: '9593',
  404: '1904',
  405: '9615',
  406: '51052',
  407: '297',
  408: '9884',
  409: '16858',
  410: '62764',
  411: '22538',
  412: '9341',
  413: '12107',
  414: '9637',
  415: '49049',
  416: '9339',
  417: '16281',
  418: '39691',
  419: '8247',
  420: '11253',
  421: '1949',
  422: '8452',
  423: '310',
  424: '27578',
  425: '954',
  426: '70160',
  427: '45243',
  428: '364',
  429: '7518',
  430: '11544',
  431: '9986',
  432: '8656',
  433: '146216',
  434: '9291',
  435: '55301',
  436: '109418',
  437: '11665',
  438: '6964',
  439: '11324',
  440: '12193',
  441: '9928',
  442: '754',
  443: '10202',
  444: '4147',
  445: '50546',
  446: '1701',
  447: '13027',
  448: '2289',
  449: '20504',
  450: '9574',
  451: '11618',
  452: '2300',
  453: '12096',
  454: '10200',
  455: '8834',
  456: '228150',
  457: '6068',
  458: '41515',
  459: '9023',
  460: '38317',
  461: '2157',
  462: '14462',
  463: '161795',
  464: '159824',
  465: '49948',
  466: '2135',
  467: '9822',
  468: '9705',
  469: '1656',
  470: '12159',
  471: '9678',
  472: '4442',
  473: '75',
  474: '330770',
  475: '9433',
  476: '19959',
  477: '11973',
  478: '11228',
  479: '77951',
  480: '5491',
  481: '10715',
  482: '10197',
  483: '9562',
  484: '9922',
  485: '9447',
  486: '274854',
  487: '8870',
  488: '9992',
  489: '36970',
  490: '10077',
  491: '76649',
  492: '293644',
  493: '453',
  494: '8587',
  495: '72545',
  496: '109451',
  497: '9533',
  498: '2023',
  499: '71880',
  500: '584',
  501: '309809',
  502: '4858',
  503: '17711',
  504: '328111',
  505: '8698',
  506: '93456',
  507: '602',
  508: '330',
  509: '953',
  510: '9693',
  511: '36657',
  512: '8909',
  513: '9802',
  514: '950',
  515: '1824',
  516: '2976',
  517: '11026',
  518: '332',
  519: '75656',
  520: '38365',
  521: '594',
  522: '15189',
  523: '11678',
  524: '6538',
  525: '10555',
  526: '1125',
  527: '4551',
  528: '612',
  529: '9567',
  530: '37821',
  531: '203801',
  532: '2539',
  533: '9297',
  534: '3172',
  535: '6520',
  536: '1439',
  537: '37958',
  538: '2026',
  539: '7450',
  540: '11375',
  541: '9425',
  542: '25769',
  543: '23685',
  544: '11866',
  545: '9741',
  546: '211672',
  547: '23629',
  548: '8688',
  549: '10153',
  550: '153518',
  551: '8676',
  552: '20829',
  553: '4349',
  554: '9718',
  555: '10808',
  556: '197',
  557: '25',
  558: '35',
  559: '11086',
  560: '10477',
  561: '1997',
  562: '6947',
  563: '3050',
  564: '2675',
  565: '809',
  566: '920',
  567: '4806',
  568: '7451',
  569: '228165',
  570: '3595',
  571: '16869',
  572: '879',
  573: '1573',
  574: '9257',
  575: '1903',
  576: '9697',
  577: '395',
  578: '23398',
  579: '10590',
  580: '117263',
  581: '200',
  582: '44943',
  583: '587',
  584: '10395',
  585: '57212',
  586: '152760',
  587: '2756',
  588: '33909',
  589: '49017',
  590: '9882',
  591: '2270',
  592: '978',
  593: '44564',
  594: '3132',
  595: '8814',
  596: '8427',
  597: '52520',
  599: '10592',
  600: '49021',
  601: '11535',
  602: '10550',
  603: '11258',
  604: '12610',
  605: '59981',
  606: '201088',
  607: '5137',
  608: '3093',
  609: '107846',
  610: '188207',
  611: '4614',
  612: '24021',
  613: '11371',
  614: '20352',
  615: '11517',
  616: '214756',
  617: '26428',
  618: '9824',
  619: '48988',
  620: '9008',
  621: '300673',
  622: '12113',
  623: '38778',
  624: '72331',
  625: '1844',
  626: '846',
  627: '9703',
  628: '857',
  629: '136797',
  630: '3981',
  631: '425',
  632: '6171',
  633: '72976',
  634: '603',
  635: '568',
  636: '9021',
  638: '9489',
  639: '12133',
  640: '9342',
  641: '41733',
  642: '227306',
  643: '5551',
  644: '9350',
  645: '9208',
  646: '4244',
  647: '1852',
  648: '11820',
  649: '76493',
  650: '345',
  651: '196867',
  652: '256591',
  653: '59962',
  654: '36648',
  655: '1880',
  656: '9440',
  657: '71679',
  658: '10483',
  659: '11412',
  660: '11983',
  661: '6795',
  662: '550',
  663: '11170',
  664: '9292',
  665: '10783',
  666: '100241',
  667: '257',
  668: '9947',
  669: '189',
  670: '12618',
  671: '253412',
  672: '1427',
  673: '818',
  674: '16577',
  675: '329',
  676: '12160',
  677: '9331',
  678: '300168',
  679: '9072',
  680: '3536',
  681: '9087',
  682: '12177',
  683: '12138',
  684: '273248',
  685: '9955',
  686: '50359',
  687: '1271',
  688: '693',
  689: '14306',
  690: '497',
  691: '11199',
  692: '9982',
  693: '210577',
  694: '2501',
  695: '710',
  696: '2275',
  697: '37165',
  698: '9837',
  699: '10708',
  700: '136400',
  701: '10992',
  702: '9654',
  703: '2642',
  704: '8916',
  705: '19899',
  706: '2119',
  707: '9641',
  708: '294254',
  709: '38167',
  710: '5994',
  711: '39514',
  712: '9563',
  713: '547',
  714: '1538',
  715: '9334',
  716: '11128',
  717: '75780',
  718: '8914',
  719: '13576',
  720: '39538',
  721: '10628',
  722: '14836',
  723: '8645',
  724: '9509',
  725: '10067',
  726: '9384',
  727: '9279',
  728: '1487',
  729: '9422',
  730: '77174',
  731: '4824',
  732: '9620',
  733: '9302',
  734: '10199',
  735: '10771',
  736: '3512',
  737: '137094',
  738: '274479',
  739: '267860',
  740: '8078',
  741: '7485',
  742: '170687',
  743: '6435',
  744: '137106',
  745: '10040',
  746: '6278',
  747: '82682',
  748: '17610',
  749: '22954',
  750: '16995',
  751: '16558',
  752: '9849',
  753: '5820',
  754: '16866',
  755: '201',
  756: '11775',
  757: '87825',
  758: '12201',
  759: '11015',
  760: '9932',
  761: '13389',
  762: '8838',
  763: '17332',
  764: '4958',
  765: '786',
  766: '9513',
  767: '11679',
  768: '38321',
  769: '14411',
  770: '8413',
  771: '10052',
  772: '9676',
  773: '9664',
  774: '2100',
  775: '10384',
  776: '137321',
  777: '123553',
  778: '11260',
  779: '9009',
  780: '11374',
  781: '2309',
  782: '8285',
  783: '210860',
  784: '2312',
  785: '9839',
  786: '381902',
  787: '13922',
  788: '293660',
  789: '9713',
  790: '190859',
  791: '257445',
  792: '9007',
  793: '889',
  794: '1370',
  795: '4942',
  796: '347969',
  797: '24438',
  798: '116741',
  799: '35791',
  800: '72431',
  801: '1813',
  802: '87428',
  803: '8840',
  804: '10589',
  805: '71676',
  806: '1722',
  807: '10022',
  808: '11358',
  809: '13',
  810: '6477',
  811: '1597',
  812: '10530',
  813: '1924',
  814: '9327',
  815: '8488',
  816: '10603',
  817: '8273',
  818: '109424',
  819: '35056',
  820: '8839',
  821: '156022',
  822: '7303',
  823: '8963',
  824: '1402',
  825: '9315',
  826: '8984',
  827: '795',
  828: '24',
  829: '11353',
  830: '393',
  831: '9618',
  832: '9374',
  833: '8584',
  834: '2320',
  835: '58224',
  836: '1729',
  837: '175574',
  838: '8077',
  839: '8818',
  840: '8195',
  841: '10586',
  842: '116149',
  843: '80035',
  844: '10632',
  845: '12117',
  846: '1792',
  847: '13260',
  848: '72197',
  849: '3580',
  850: '12123',
  851: '9566',
  852: '9833',
  853: '4517',
  854: '8202',
  855: '16072',
  856: '34314',
  857: '19724',
  858: '145220',
  859: '14623',
  860: '42297',
  861: '2841',
  862: '802',
  863: '10375',
  864: '36586',
  865: '11321',
  866: '70074',
  867: '242',
  868: '9621',
  869: '1819',
  870: '8536',
  871: '8046',
  872: '1717',
  873: '479',
  874: '9444',
  875: '824',
  876: '11456',
  877: '261023',
  878: '3683',
  879: '22803',
  880: '285923',
  881: '39437',
  882: '1950',
  883: '640',
  884: '97630',
  885: '9767',
  886: '11631',
  887: '32856',
  888: '6519',
  889: '8741',
  890: '49520',
  891: '1850',
  892: '524',
  893: '26389',
  894: '11817',
  895: '2123',
  896: '9907',
  897: '9969',
  898: '18239',
  899: '808',
  900: '38050',
  901: '8367',
  902: '9390',
  903: '72105',
  904: '2898',
  905: '10312',
  906: '109443',
  907: '2022',
  908: '37686',
  909: '462',
  910: '9919',
  911: '187017',
  912: '628',
  913: '10201',
  914: '302699',
  915: '9441',
  916: '274167',
  917: '224141',
  918: '388',
  919: '2112',
  920: '10329',
  921: '74465',
  922: '13811',
  923: '6877',
  924: '10320',
  925: '50646',
  926: '8920',
  927: '13673',
  928: '60308',
  929: '6950',
  930: '225574',
  931: '13836',
  932: '752',
  933: '6038',
  934: '9975',
  935: '11451',
  936: '12103',
  937: '60304',
  938: '2251',
  939: '46529',
  940: '231',
  941: '300671',
  942: '228326',
  943: '9754',
  944: '66',
  945: '4421',
  946: '2649',
  947: '588',
  948: '10393',
  949: '71552',
  950: '9631',
  951: '216282',
  952: '306',
  953: '928',
  954: '205587',
  955: '6623',
  956: '1577',
  957: '9801',
  958: '2116',
  959: '9624',
  960: '14199',
  961: '1907',
  962: '4599',
  963: '22832',
  964: '10390',
  965: '9879',
  966: '38579',
  967: '44603',
  968: '11892',
  969: '9691',
  970: '1248',
  971: '12220',
  972: '72710',
  973: 1255,
  974: '10782',
  975: '9573',
  976: '4959',
  977: '10061',
  978: '10386',
  979: '421',
  980: '316152',
  981: '11615',
  982: '13498',
  983: '241554',
  984: '2252',
  985: '11968',
  986: '10047',
  987: '38319',
  988: '69668',
  989: '9770',
  990: '11212',
  991: '10533',
  992: '38363',
  993: '9923',
  994: '11863',
  995: '18501',
  996: '109491',
  997: '9275',
  998: '329833',
  999: '12634',
  1000: '10416',
  1001: '47327',
  1002: '15268',
  ...},
 'title': {0: 'Avatar',
  1: "Pirates of the Caribbean: At World's End",
  2: 'Spectre',
  3: 'The Dark Knight Rises',
  4: 'John Carter',
  5: 'Spider-Man 3',
  6: 'Tangled',
  7: 'Avengers: Age of Ultron',
  8: 'Harry Potter and the Half-Blood Prince',
  9: 'Batman v Superman: Dawn of Justice',
  10: 'Superman Returns',
  11: 'Quantum of Solace',
  12: "Pirates of the Caribbean: Dead Man's Chest",
  13: 'The Lone Ranger',
  14: 'Man of Steel',
  15: 'The Chronicles of Narnia: Prince Caspian',
  16: 'The Avengers',
  17: 'Pirates of the Caribbean: On Stranger Tides',
  18: 'Men in Black 3',
  19: 'The Hobbit: The Battle of the Five Armies',
  20: 'The Amazing Spider-Man',
  21: 'Robin Hood',
  22: 'The Hobbit: The Desolation of Smaug',
  23: 'The Golden Compass',
  24: 'King Kong',
  25: 'Titanic',
  26: 'Captain America: Civil War',
  27: 'Battleship',
  28: 'Jurassic World',
  29: 'Skyfall',
  30: 'Spider-Man 2',
  31: 'Iron Man 3',
  32: 'Alice in Wonderland',
  33: 'X-Men: The Last Stand',
  34: 'Monsters University',
  35: 'Transformers: Revenge of the Fallen',
  36: 'Transformers: Age of Extinction',
  37: 'Oz: The Great and Powerful',
  38: 'The Amazing Spider-Man 2',
  39: 'TRON: Legacy',
  40: 'Cars 2',
  41: 'Green Lantern',
  42: 'Toy Story 3',
  43: 'Terminator Salvation',
  44: 'Furious 7',
  45: 'World War Z',
  46: 'X-Men: Days of Future Past',
  47: 'Star Trek Into Darkness',
  48: 'Jack the Giant Slayer',
  49: 'The Great Gatsby',
  50: 'Prince of Persia: The Sands of Time',
  51: 'Pacific Rim',
  52: 'Transformers: Dark of the Moon',
  53: 'Indiana Jones and the Kingdom of the Crystal Skull',
  54: 'The Good Dinosaur',
  55: 'Brave',
  56: 'Star Trek Beyond',
  57: 'WALL·E',
  58: 'Rush Hour 3',
  59: '2012',
  60: 'A Christmas Carol',
  61: 'Jupiter Ascending',
  62: 'The Legend of Tarzan',
  63: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
  64: 'X-Men: Apocalypse',
  65: 'The Dark Knight',
  66: 'Up',
  67: 'Monsters vs Aliens',
  68: 'Iron Man',
  69: 'Hugo',
  70: 'Wild Wild West',
  71: 'The Mummy: Tomb of the Dragon Emperor',
  72: 'Suicide Squad',
  73: 'Evan Almighty',
  74: 'Edge of Tomorrow',
  75: 'Waterworld',
  76: 'G.I. Joe: The Rise of Cobra',
  77: 'Inside Out',
  78: 'The Jungle Book',
  79: 'Iron Man 2',
  80: 'Snow White and the Huntsman',
  81: 'Maleficent',
  82: 'Dawn of the Planet of the Apes',
  83: 'The Lovers',
  84: '47 Ronin',
  85: 'Captain America: The Winter Soldier',
  86: 'Shrek Forever After',
  87: 'Tomorrowland',
  88: 'Big Hero 6',
  89: 'Wreck-It Ralph',
  90: 'The Polar Express',
  91: 'Independence Day: Resurgence',
  92: 'How to Train Your Dragon',
  93: 'Terminator 3: Rise of the Machines',
  94: 'Guardians of the Galaxy',
  95: 'Interstellar',
  96: 'Inception',
  97: 'Shin Godzilla',
  98: 'The Hobbit: An Unexpected Journey',
  99: 'The Fast and the Furious',
  100: 'The Curious Case of Benjamin Button',
  101: 'X-Men: First Class',
  102: 'The Hunger Games: Mockingjay - Part 2',
  103: "The Sorcerer's Apprentice",
  104: 'Poseidon',
  105: 'Alice Through the Looking Glass',
  106: 'Shrek the Third',
  107: 'Warcraft',
  108: 'Terminator Genisys',
  109: 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
  110: 'Pearl Harbor',
  111: 'Transformers',
  112: 'Alexander',
  113: 'Harry Potter and the Order of the Phoenix',
  114: 'Harry Potter and the Goblet of Fire',
  115: 'Hancock',
  116: 'I Am Legend',
  117: 'Charlie and the Chocolate Factory',
  118: 'Ratatouille',
  119: 'Batman Begins',
  120: 'Madagascar: Escape 2 Africa',
  121: 'Night at the Museum: Battle of the Smithsonian',
  122: 'X-Men Origins: Wolverine',
  123: 'The Matrix Revolutions',
  124: 'Frozen',
  125: 'The Matrix Reloaded',
  126: 'Thor: The Dark World',
  127: 'Mad Max: Fury Road',
  128: 'Angels & Demons',
  129: 'Thor',
  130: 'Bolt',
  131: 'G-Force',
  132: 'Wrath of the Titans',
  133: 'Dark Shadows',
  134: 'Mission: Impossible - Rogue Nation',
  135: 'The Wolfman',
  136: 'Bee Movie',
  137: 'Kung Fu Panda 2',
  138: 'The Last Airbender',
  139: 'Mission: Impossible III',
  140: 'White House Down',
  141: 'Mars Needs Moms',
  142: 'Flushed Away',
  143: 'Pan',
  144: 'Mr. Peabody & Sherman',
  145: 'Troy',
  146: "Madagascar 3: Europe's Most Wanted",
  147: 'Die Another Day',
  148: 'Ghostbusters',
  149: 'Armageddon',
  150: 'Men in Black II',
  151: 'Beowulf',
  152: 'Kung Fu Panda 3',
  153: 'Mission: Impossible - Ghost Protocol',
  154: 'Rise of the Guardians',
  155: 'Fun with Dick and Jane',

In [ ]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [ ]:
pickle.dump(similarity,open('similarity.pkl','wb'))

Local URL: http://localhost:8501
  Network URL: http://192.168.1.38:8501